### ISSUE TITLE
Steam Tinker Launch(For all distros other than Arch)

### ISSUE THREAD

**Issue by trenton4k** [Ahmed-Al-Balochi/LibreGaming#11]
will be a good add to LibreGaming
https://github.com/frostworx/steamtinkerlaunch

**Comment by ahmed-al-balochi** [comment]
I will see if I can add it. 
Thanks.

**Comment by ahmed-al-balochi** [comment]
Hi @trenton4k,
The option to install Steam Tinker Launch will only be available for Arch Linux. because it will be very tough to support it on other distros because of the dependencies it uses.
if you know a way to install all the dependencies on the distros that LibreGaming supports please share it.

**Comment by ahmed-al-balochi** [comment]
If anyone knows how to install Steam Tinker Launch for all distros other than Arch Linux, please share it.

**Comment by frostworx** [comment]
Hi, just found your project. I'm the author of steamtinkerlaunch, so thanks for suggesting it here, @trenton4k and thanks for adding it @Ahmed-Al-Balochi :)
Like with every program, every distribution requires people who are willing to create and maintain a package for that program,
so it can be installed easily by the user.
Several people are already working on install packages for various distros _(some can be found [on github](https://github.com/search?q=steamtinkerlaunch&type=code))_, which might help to create packages for distributions which don't have one yet.
The main "problem" with packaging stl is, that yad (zenity fork, the gui toolkit used in stl) is often very outdated on several distributions and therefore is too old for stl to work correctly. So people who are interested in maintaining a stl package _(which is very easy, as I do not change dependencies very often)_ should check if a new enough yad version is available on their distribution and bump the yad package as well if not.

All other stl [dependencies](https://github.com/frostworx/steamtinkerlaunch#requirements) _(or check the [PKGBUILD](https://aur.archlinux.org/packages/steamtinkerlaunch/))_ should be available on every distribution.
stl also ships a simple Makefile _(`make install` is enough, stl is written in `bash`)_,
so when installing the dependencies manually and making sure yad is available on the one or other way, stl should *just work*.
yad is simple to compile from source, but I even added several workarounds to use yad without depending on a system installation: https://github.com/frostworx/steamtinkerlaunch/wiki/Custom-Yad

I hope that helped a bit :) If anything is unclear feel free to ask!

Btw, I'm looking for contributors, as I will soon have much less time for working on stl: https://github.com/frostworx/steamtinkerlaunch/issues/309
Any help would be great!

**Comment by ahmed-al-balochi** [comment]
I am very busy now. But I will see what I can do about it.
Thank you suggesting solutions @frostworx .

**Comment by frostworx** [comment]
fyi: Solus has an [official steamtinkerlaunch package](https://packages.getsol.us/unstable/s/steamtinkerlaunch/) since Monday _(just added it to my `README`)_ :)

**Comment by ahmed-al-balochi** [comment]
> fyi: Solus has an [official steamtinkerlaunch package](https://packages.getsol.us/unstable/s/steamtinkerlaunch/) since Monday _(just added it to my `README`)_ :)

That's great, but I don't support Solus.
