### ISSUE TITLE
proton-ge not installed to correct location

### ISSUE THREAD

**Issue by T2hhbmEK** [Ahmed-Al-Balochi/LibreGaming#12]
For short, do not run `LibreGaming -a`.

Details:
Running `LibreGaming -a` with a clean home directory, there will be no `.steam` directory.
When installing `proton-ge` using `protonup`, `~/.steam/root/compatibilitytools.d` will be auto created(`mkdir -p` maybe).
However, at this time, steam has not been run.
In fact, at first run, steam will creates `~/.steam` directories and make a soft link of your real steam root to `~/.steam/root` .
For arch linux, it shoud be a soft link of `~/.local/share/Steam`.
These cause a problem that proton-ge is installed to a location which is not the real steam root.
What's more, when steam starts, it detects `~/.steam/root` already exists and will not create the soft link for you.

Fix option 1:
To solve this problem, do not run `-a` option with a clean install.
Run`-p` after open steam at least once.

Fix option 2:
Or just run `-a` and manually fix it.
For arch linux, this can be fixed through following commands.
```bash
mv ~/.steam/root/compatibilitytools.d ~/.local/share/Steam && \
rmdir ~/.steam/root && \
ln -sf ~/.local/share/Steam ~/steam/root
```

**Comment by ahmed-al-balochi** [comment]
Ok I will see what I can do.

**Comment by ahmed-al-balochi** [comment]
Verified the issue on my VMs. and did what you said in option 1, now the fix is in the latest release.
Thanks a lot for the issue.
