### ISSUE TITLE
No .bashrc or .zshrc files

### ISSUE THREAD

**Issue by alexholox** [Ahmed-Al-Balochi/LibreGaming#13]
LibreGaming command not found. The files you listed simply don't exist. There aren't anywhere and this needs an update. Fix it please.

openSUSE Tumbleweed, followed the instructions religiously and there is absolutely no .bashrc or .zshrc on any part, nor where the guide says nor in /LibreGaming, anywhere. It does not exist. Fix please, thanks.

**Comment by ahmed-al-balochi** [comment]
Hi, 
* Any file or folder that starts with a dot(.) is always hidden by default. So, you need to show them.
* to show the files using a terminal:
```
ls -alh
```
* You can access your shell files using this command.
* for bash
```
nano .bashrc
```
* for zsh
```
nano .zshrc
```
* after you access the shell file you need to add the following lines to your shell file.
```
### PATH

if [ -d "$HOME/.local/bin" ] ;
  then PATH="$HOME/.local/bin:$PATH"
fi
```

**Comment by alexholox** [comment]
```
GNU nano 5.8                                  .bashrc                                            
# Sample .bashrc for SUSE Linux
# Copyright (c) SUSE Software Solutions Germany GmbH

# There are 3 different types of shells in bash: the login shell, normal shell
# and interactive shell. Login shells read ~/.profile and interactive shells
# read ~/.bashrc; in our setup, /etc/profile sources ~/.bashrc - thus all
# settings made here will also take effect in a login shell.
#
# NOTE: It is recommended to make language settings in ~/.profile rather than
# here, since multilingual X sessions would not work properly if LANG is over-
# ridden in every subshell.

test -s ~/.alias && . ~/.alias || true

### PATH

if [ -d "$HOME/.local/bin" ] ;
  then PATH="$HOME/.local/bin:$PATH"
fi

```


---

This is what I get from using nano .bashrc, is it normal? I don't seem to be able to edit or doing anything with this. What should I do to access the file?

**Comment by ahmed-al-balochi** [comment]
Yes. You need to close the terminal after you paste the PATH. and I have used SUSE to test my LibreGaming and when I pasted the PATH it worked.
