### ISSUE TITLE
Can i fork this

### ISSUE THREAD

**Issue by OpenDevloper** [Ahmed-Al-Balochi/LibreGaming#15]
hey i wanna make my own version of it am i allowed to do so?

**Comment by ahmed-al-balochi** [comment]
Yes, you can it's open source.

**Comment by OpenDevloper** [comment]
oh thanks man :)
i wanted to make it my own ok now the case is that i have to install linux because there was my exams having some issues with linux so i had to make a complete migration to "michale soft" winbows
i will clone the repository when i am linux nd that is today, i will work it and upload it on my github (this account only)

**Comment by OpenDevloper** [comment]
ok thanks for solving my issue ( close the issue)

**Comment by ahmed-al-balochi** [comment]
Good luck 👍
