### ISSUE TITLE
Add MInigalaxy

### ISSUE THREAD

**Issue by ecficies** [Ahmed-Al-Balochi/LibreGaming#16]
Minigalaxy - A simple GOG client for Linux

Would be a great addition as a GOG client.
Arguements should be one of these:
 - -m
 - -mg
 - --minigalaxy

https://sharkwouter.github.io/minigalaxy/
https://github.com/sharkwouter/minigalaxy

**Comment by ahmed-al-balochi** [comment]
Ok. I will see if I can add it.
Thanks btw.

**Comment by ahmed-al-balochi** [comment]
Just added support to it.
Enjoy
