### ISSUE TITLE
Add GameHub

### ISSUE THREAD

**Issue by ecficies** [Ahmed-Al-Balochi/LibreGaming#18]
GameHub - All your games in one place

Would be a great addition as an overall game launcher.
Arguements should be one of these:

- -gh
- --gamehub

https://tkashkin.github.io/projects/gamehub
https://github.com/tkashkin/GameHub

**Comment by ahmed-al-balochi** [comment]
@grgivs 
I think Lutris already does this kind of work. it can host all your games in one place.
