### ISSUE TITLE
how about uninstall

### ISSUE THREAD

**Issue by pvlalxandru** [Ahmed-Al-Balochi/LibreGaming#19]
300 packages, 300 packages. just cause i used -g option. how about uninstall huh?

**Comment by Ahmed-Al-Balochi** [comment]
You can uninstall most these packages but not all of them. That's is why I didn't make an option. This is also the case if install those packages yourself.

**Comment by pvlalxandru** [comment]
ok man i got mad cus after 300 packages game still no work lol. is there a list of packages that got installed or shall i go find that out myself

**Comment by Ahmed-Al-Balochi** [comment]
No sorry about that. Because the dependencies change with time.
