### ISSUE TITLE
opensuse tumbleweed support

### ISSUE THREAD

**Issue by 10leej** [Ahmed-Al-Balochi/LibreGaming#2]
The package manager is zypper
all the packages are in the main + packman repo's

syntax is just an easy "sudo zypper install"
If you want you can  firstadd a hook to enable codecs, which also sets up packman "sudo zypper opi" then "opi codes"

**Comment by ahmed-al-balochi** [comment]
I will work on it as soon as I have time.
Thanks for your feedback.

**Comment by ahmed-al-balochi** [comment]
Just merged the commit that has support for OpenSUSE tumbleweed.
Enjoy :)

**Comment by 10leej** [comment]
You should clarify that opensuse needs the packman repository setup (opi sets it up for you with codecs which you also need for steam anyways)

**Comment by ahmed-al-balochi** [comment]
I ran this command and it made me install all the needed packages like steam on SUSE.
The command: sudo zypper addrepo -cfp 90 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/' packman

**Comment by 10leej** [comment]
At the very least mention that in the docs, I think that command errors is a user already has packaman enabled, I dont have an active installation currently to verify that.

**Comment by ahmed-al-balochi** [comment]
I got that command from this document page on SUSE website: https://en.opensuse.org/Additional_package_repositories
