### ISSUE TITLE
Add support for WineGE

### ISSUE THREAD

**Issue by ahmed-al-balochi** [Ahmed-Al-Balochi/LibreGaming#20]
I want to add support to WineGE in my LibreGaming tool just like ProtonGE.

**Comment by cloudishBenne** [comment]
@Ahmed-Al-Balochi 
I think after refactoring the protonup code we could fork it to a new wineup. I first thought about adding it to protonup (or however i name it) but i think the best way is still "Do one thing and do it well".

**Comment by ahmed-al-balochi** [comment]
@ [cloudishBenne](https://github.com/cloudishBenne)
I think we can achieve both on the same program without it being too complex because we are following the same idea where we download a GE build and install it where it supposed to be.

**Comment by ahmed-al-balochi** [comment]
WineGE is now available and easy to install on Lutris, which are already supported by LibreGaming.
