### ISSUE TITLE
LibreGaming -p stopped working with new protonGE naming scheme

### ISSUE THREAD

**Issue by laclcia** [Ahmed-Al-Balochi/LibreGaming#25]
since ProtonGE changed the naming schemes the update download's but fail's to find locate the file "sha512sum" and crashes out.

```
Ready to download Proton-GE-Proton7-5 
Size      : 395.8 MiB 
Published : 2022-03-02
Continue? (Y/n): y
Downloaded 100.00% - 395.8 MiB / 395.8 MiB   
[INFO] Installed in: /home/laclcia/.steam/root/compatibilitytools.d/Proton-GE-Proton7-5
Traceback (most recent call last):
  File "/home/laclcia/.local/bin/protonup", line 8, in <module>
    sys.exit(main())
  File "/home/laclcia/.local/lib/python3.10/site-packages/protonup/__init__.py", line 4, in main
    return main()
  File "/home/laclcia/.local/lib/python3.10/site-packages/protonup/cli.py", line 33, in main
    get_proton(version=args.tag, yes=args.yes, dl_only=args.download,
  File "/home/laclcia/.local/lib/python3.10/site-packages/protonup/api.py", line 155, in get_proton
    open(checksum_dir, 'w').write(download_checksum)
FileNotFoundError: [Errno 2] No such file or directory: '/home/laclcia/.steam/root/compatibilitytools.d/Proton-GE-Proton7-5/sha512sum'
```

output above.
has been happening since Proton-GE-Proton7-2 (diddnt get the chance to test on -1.) 
i have tried updating libregaming  with `pip3 install LibreGaming -U` before posting obviously. 

if that help's i am running Manjaro Linux x86_64 lastest as of writing this. have tried on the default lastest kernel 5.15.25 manjaro. and on 5.15.25-xanmod1-tt-1 with same result's.

**Comment by ahmed-al-balochi** [comment]
Thank you for posting. I will look into it.

**Comment by LyCH-OS** [comment]
Hi, I'm also having the issue above. Manjaro Linux XFCE.

**Comment by laclcia** [comment]
> Thank you for posting. I will look into it.

thank you. this is a really nice tool. thank you for making and maintaining it ^_^

**Comment by ahmed-al-balochi** [comment]
Just checked the ProtonUP tool on Github, its the tool that I depend on for the ```libregaming  -p ```  looks like someone already submitted a pull request fixing the issue you can check it  here: https://github.com/AUNaseef/protonup/pull/26
The only thing is remaining is for the ProtonUp maintainer to merge the pull request hopefully soon.

**Comment by cloudishBenne** [comment]
@Ahmed-Al-Balochi Do you have a possibility to directly contact the maintainer of protonup? Until the patch gets merged one can clone from my fork and install that from source.

**Comment by ahmed-al-balochi** [comment]
The only other way of contacting him is through Twitter and I just went there. He says he is working on a rewrite of the program.
![image](https://user-images.githubusercontent.com/67327078/157214896-3666a41f-3f62-4c37-85ff-13c4e25de942.jpeg)

**Comment by cloudishBenne** [comment]
Thank you for contacting him.
It would be great if he could join discussion on his repo. I think when he purges the option to install an old release many scripts will break and protonup will die... One should not kill backwards compatibility when there is no need to.

I'm also rewriting the code atm because he did not answer and he is right, that the code is a mess. Would be great to work together here on github.

**Comment by ahmed-al-balochi** [comment]
He is going to have support to install old versions before the name change and after. So, Protonup might die but there will be a replacement for it.

**Comment by laclcia** [comment]
thank you. this is amazing ^_^.

**Comment by ahmed-al-balochi** [comment]
Installing ProtonGE is Working now by using [Protonup-ng](https://github.com/cloudishBenne/protonup-ng). You can now use the latest LibreGaming version 0.2.3 to download ProtonGE.
* To install the latest release [click here](https://github.com/Ahmed-Al-Balochi/LibreGaming#installation).
