### ISSUE TITLE
Winetricks is a dependency of ProtonGE

### ISSUE THREAD

**Issue by BrodieRobertson** [Ahmed-Al-Balochi/LibreGaming#3]
At least according to the ProtonGE github this is the case, however, it's not included inside the package install list.

**Comment by ahmed-al-balochi** [comment]
added it and testing it on my local machine.
Thanks for the feedback, love your videos btw.

**Comment by ahmed-al-balochi** [comment]
Done with adding winetricks. Everything is working on the supported distros.
