### ISSUE TITLE
LibreGaming adds the Wine Ubuntu 20.04 Focal Fossa repository, no matter the Ubuntu version the user is running

### ISSUE THREAD

**Issue by logix2** [Ahmed-Al-Balochi/LibreGaming#5]
LibreGaming adds the Wine Ubuntu 20.04 Focal Fossa repository, no matter the Ubuntu version the user is running, [here](https://github.com/Ahmed-Al-Balochi/LibreGaming/blob/main/LibreGaming/LibreGaming.py#L18).

**Comment by ahmed-al-balochi** [comment]
Ok I will see what I can do to fix it. Thanks for he feedback

**Comment by ahmed-al-balochi** [comment]
Now LibreGaming should install the right PPA based on the Ubuntu release.
Thanks again for pointing the issue.
