### ISSUE TITLE
LibreGaming -a has broken download links?

### ISSUE THREAD

**Issue by fredrikscode** [Ahmed-Al-Balochi/LibreGaming#6]
Hi there,

Love the project. I decided to try it out today after watching TechHut and used the installation through pip3. It got stuck while trying to download packages:

**"warning: failed to retrieve some files"**

**lib32-mpg123-1.28.2-1-x86_64.pkg.tar.zst failed to download**

What seemed relevant from the console can be found here: [https://pastebin.com/HZ7vU523](https://pastebin.com/HZ7vU523) - To avoid the spam :) I'll be installing it using the other method instead but thought I'd share this if it's useful.

**Comment by ahmed-al-balochi** [comment]
Hi,
If I understand correctly you tried to install LibreGaming using pip3, but it gave you those errors/failed while installing. Right?
Also, Please tell me whats is your distro?
Lastly, the URL you provided is not working with me.
Thanks.

**Comment by fredrikscode** [comment]
That's correct. I'm on Arch. I tried the link again and it works for me, it's just a regular pastebin link.. hm

**Comment by ahmed-al-balochi** [comment]
I think I know whats the problem. do you have the Multilib repo enabled? because it's the one that contains 32bit packages needed for WINE gaming.
You can enable it from [here](https://wiki.archlinux.org/title/official_repositories#multilib)

**Comment by fredrikscode** [comment]
Unfortunately I do have multilib enabled already

**Comment by ahmed-al-balochi** [comment]
Ok, I will investigate further.

**Comment by ahmed-al-balochi** [comment]
I did a clean install to both Arch and Manjaro to see whats the problem. that package that was giving you errors installs perfectly on both of them.
I really don't know what is causing the problem for you. But if you have weak internet and you are using parallel downloads it might be the reason for the problem. Or it might be a bad repo sync. 
I wish I could help you more, if you still have any insight as to what is causing the problem feel free to share it. 
Thank you
