### ISSUE TITLE
Error installing Gaming pacages

### ISSUE THREAD

**Issue by heli-aviator** [Ahmed-Al-Balochi/LibreGaming#7]
Hi, thank you for the project I'm having some trouble with it though.
Manjaro KDE, Kernal 5.14

when I run the command LibreGaming -g it tells me I need to be root, with root=
```
sudo LibreGaming --gaming
sudo LibreGaming -g
sudo LibreGaming -a
```
Is producing this output
```
Traceback (most recent call last):
  File "/home/kds/.local/bin/LibreGaming", line 5, in <module>
    from LibreGaming import main
ModuleNotFoundError: No module named 'LibreGaming' 
```

I tried LlibreGaming -a as well but get the same message. what what do I need to do?

**Comment by ahmed-al-balochi** [comment]
Just committed the fix for the error. it should work now. 
Also, I made a new pip release with the fix included. update the package if you are using pip or clone the repo.
Thank you.
