### ISSUE TITLE
Why python?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Ahmed-Al-Balochi/LibreGaming#9]
Hey Ahmed, as a start i want to say thank you for your great work :)
Second, I really was wondring, why python? i mean most of your calls are inside terminal anyways so why python in first place, why not just bash script? if you allow me (aka want) i can play around and try to make a bash script (i'm learning it and it would be a good challange) so do you want bash script along side your python script or just python?

و عارف الأنجليزى بتاعى مش حلو اوى 😅

**Comment by ahmed-al-balochi** [comment]
Hi,
Thank you for your questions, let start by saying that there is no harm in cloning the project and rewrite it in bash and then publish it on your Github page. After all that is what open source allows. However, I want keep this project written in Python.
As to why using Python? Well I wanted a new challenge. You see I already have experience in shell scripting, C++, and Java. But not Python. And Python has a lot of great libraries that makes programming in it easy and straightforward.
I hope this answers your questions.
Thanks again. 
الانجليزي حقك تمام😊

**Comment by EsmailELBoBDev2** [comment]
Okay good news and bad news.
I just finished my rewrite of it using bash (that works in Arch linux for now) and if you want a PR (so user can use both options) -- also i tried to implement broodie's feedback

**Comment by ahmed-al-balochi** [comment]
You can create your own project or clone this one and rewrite it on your own repo. But I won't accept any pull request that does't fit this repo.
Thank you

**Comment by AussieEevee** [comment]
I was about to ask this myself. I was wondering because python adds some extra system requirements thats not usually installed by default

**Comment by ahmed-al-balochi** [comment]
Well this program already uses protonup which is a python program. So even if I didn't program LibreGaming in python you will still need some of those system requirements you mentioned. Also, its very easy to package python programs into pip. I hope this answers you question.
